#!/bin/sh
cd `dirname $0`

case "${OSTYPE}" in
darwin*)
  XMODIFIERS=@im=none java -Djava.library.path=./lib -cp ./NullpoMino.jar:lib/log4j.jar:lib/swing-layout.jar:lib/swing-worker.jar:lib/lwjgl.jar:lib/lwjgl-platform-natives-osx.jar:lib/jorbis.jar:lib/jinput.jar:lib/jinput-platform-natives-osx.jar:lib/jutils.jar mu.nu.nullpo.gui.swing.NullpoMinoSwing;;
linux*)
  XMODIFIERS=@im=none java -Djava.library.path=./lib -cp ./NullpoMino.jar:lib/log4j.jar:lib/swing-layout.jar:lib/swing-worker.jar:lib/lwjgl.jar:lib/lwjgl-platform-natives-linux.jar:lib/jorbis.jar:lib/jinput.jar:lib/jinput-platform-natives-linux.jar:lib/jutils.jar mu.nu.nullpo.gui.swing.NullpoMinoSwing;;
esac